# Generated by Django 5.2.4 on 2025-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_category_name_alter_instructor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد محصول', null=True),
        ),
    ]
