# Generated by Django 5.2.4 on 2025-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ویژگی اضافی', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturePrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ویژگی اصلی', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات ', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features_additional',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.featureadditional'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_primary',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.featureprimary'),
        ),
    ]
