# Generated by Django 5.2.4 on 2025-07-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_featureadditional_featureprimary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, help_text='نام دسته\u200cبندی محصول را وارد کنید.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='featureadditional',
            name='name',
            field=models.CharField(help_text='نام ویژگی اضافی محصول را وارد کنید.', max_length=255),
        ),
        migrations.AlterField(
            model_name='featureprimary',
            name='name',
            field=models.CharField(help_text='نام ویژگی اصلی محصول را وارد کنید.', max_length=255),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات مربوط به مدرس را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر مدرس را بارگذاری کنید.', null=True, upload_to='instructors/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, help_text='نام مدرس را وارد کنید.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyers_count',
            field=models.IntegerField(blank=True, default=0, help_text='تعداد خریداران محصول.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی محصول را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ ایجاد محصول.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات محصول را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.DurationField(blank=True, help_text='مدت زمان دوره را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features_additional',
            field=models.ManyToManyField(blank=True, help_text='ویژگی\u200cهای اضافی محصول را انتخاب کنید.', related_name='products', to='Products.featureadditional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features_primary',
            field=models.ManyToManyField(blank=True, help_text='ویژگی\u200cهای اصلی محصول را انتخاب کنید.', related_name='products', to='Products.featureprimary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر محصول را بارگذاری کنید.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='مدرسین این محصول را انتخاب کنید.', related_name='products', to='Products.instructor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], help_text='سطح محصول (مبتدی، متوسط، پیشرفته) را انتخاب کنید.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='نام محصول را وارد کنید.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قیمت محصول را وارد کنید.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_count',
            field=models.IntegerField(blank=True, help_text='تعداد ویدیوهای دوره را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0, help_text='تعداد بازدیدهای محصول.', null=True),
        ),
    ]
