# Generated by Django 5.2.4 on 2025-07-14 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_category_name_alter_featureadditional_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان سر فصل دوره را وارد کنید.', max_length=255)),
                ('product', models.ForeignKey(help_text='دوره مرتبط را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان ویدیو را وارد کنید.', max_length=255)),
                ('link', models.URLField(help_text='لینک ویدیو را وارد کنید.')),
                ('content', models.ForeignKey(help_text='سر فصل مرتبط با ویدیو را انتخاب کنید.', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Products.coursecontent')),
            ],
        ),
    ]
