# Generated by Django 5.2.4 on 2025-07-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_category_description_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی محصول را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category'),
        ),
    ]
