# Generated by Django 5.2.4 on 2025-07-15 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_tag_product_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='description_secondary',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول را وارد کنید.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_certificate',
            field=models.BooleanField(blank=True, default=False, help_text='آیا این محصول مدرک می\u200cدهد؟', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Products.product'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
