# Generated by Django 5.2.4 on 2025-07-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_author_tag_blog_updated_at_blog_authors_blog_tags'),
        ('Products', '0010_enrollment_delete_tag_product_description_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='product',
            field=models.ForeignKey(blank=True, help_text='محصول (دوره) مرتبط با ویدیو را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='Blog.tag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.ForeignKey(blank=True, help_text='سر فصل مرتبط با ویدیو را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Products.coursecontent'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, help_text='لینک ویدیو را وارد کنید.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان ویدیو را وارد کنید.', max_length=255, null=True),
        ),
    ]
